#!/usr/bin/env bash

# MIT license (c) 2021-2024 https://github.com/slowpeek
# Homepage: https://github.com/slowpeek/kdeconnect-focal-ciphers

# Tailored for ubuntu 20.04+ and derivatives.

set -eu

ssl_cnf=/etc/ssl/openssl.cnf

ssl_conf_1x() {
    cat <<EOF
openssl_conf = default_conf

$(< "$ssl_cnf")

[default_conf]
ssl_conf = ssl_sect

[ssl_sect]
system_default = system_default_sect

[system_default_sect]
CipherString = DEFAULT:@SECLEVEL=1
EOF
}

ssl_conf_3x() {
   sed -E 's,SECLEVEL=[[:digit:]],SECLEVEL=0,' "$ssl_cnf"
}

main() {
    local bin=/usr/lib/x86_64-linux-gnu/libexec/kdeconnectd
    local custom_ssl_cnf=$XDG_RUNTIME_DIR/openssl.kdeconnectd.cnf

    # Check if kdeconnect is installed.
    [[ ! -f $bin ]] && exit

    # Check if the daemon is up for the current user.
    pgrep -x kdeconnectd -u "$EUID" &>/dev/null && exit

    local ssl_pkg_version
    ssl_pkg_version=$(dpkg-query -Wf '${version}\n' openssl)

    # It was good till 1.1.1d-2ubuntu2
    dpkg --compare-versions "$ssl_pkg_version" lt 1.1.1d-2ubuntu2 && exit

    case $ssl_pkg_version in
        1.*)
            ssl_conf_1x > "$custom_ssl_cnf" ;;
        3.*)
            ssl_conf_3x > "$custom_ssl_cnf" ;;
        *)
            exit 1 ;;
    esac

    exec env OPENSSL_CONF="$custom_ssl_cnf" "$bin"
}

[[ ! ${BASH_SOURCE[0]##*/} == "${0##*/}" ]] || main "$@"
