#!/usr/bin/env bash

# MIT license (c) 2021-2024 https://github.com/slowpeek
# Homepage: https://github.com/slowpeek/kdeconnect-focal-ciphers

# Tailored for ubuntu 20.04+ and derivatives.

set -eu

ssl_cnf=/etc/ssl/openssl.cnf
SELF_DIR=$(dirname "$(readlink -f "$0")")

main() {
    local bin=/usr/lib/x86_64-linux-gnu/libexec/kdeconnectd
    local custom_ssl_cnf=$XDG_RUNTIME_DIR/openssl.kdeconnectd.cnf

    # Check if kdeconnect is installed.
    [[ ! -f $bin ]] && exit

    # Check if the daemon is up for the current user.
    pgrep -x kdeconnectd -u "$EUID" &>/dev/null && exit

    local ssl_pkg_version
    ssl_pkg_version=$(dpkg-query -Wf '${version}\n' openssl)

    # It was good till 1.1.1d-2ubuntu2
    dpkg --compare-versions "$ssl_pkg_version" lt 1.1.1d-2ubuntu2 && exit

    local patched_ssl_cnf=$SELF_DIR/cnf/patched/$(md5sum "$ssl_cnf" | awk '{ print $1 }')
    local env=()

    if [[ -f $patched_ssl_cnf ]]; then
        cat "$patched_ssl_cnf" > "$custom_ssl_cnf"
        env+=(env OPENSSL_CONF="$custom_ssl_cnf")
    fi

    exec "${env[@]}" "$bin"
}

[[ ! ${BASH_SOURCE[0]##*/} == "${0##*/}" ]] || main "$@"
